In [1]:
import pandas as pd

data = pd.read_csv(
    "../dataset/Skin_NonSkin.txt",
    delim_whitespace=True,
    header=None,
    names=["R", "G", "B", "Label"]
)

data.head()

C:\Users\vivek\AppData\Local\Temp\ipykernel_6356\3408351514.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(

    R   G    B  Label
0  74  85  123      1
1  73  84  122      1
2  72  83  121      1
3  70  81  119      1
4  70  81  119      1

In [2]:
print("Total rows:", data.shape[0])
print(data['Label'].value_counts())

Total rows: 245057
Label
2    194198
1     50859
Name: count, dtype: int64

In [3]:
import cv2
import numpy as np

def rgb_to_hsv(row):
    rgb = np.uint8([[[row['R'], row['G'], row['B']]]])
    hsv = cv2.cvtColor(rgb, cv2.COLOR_RGB2HSV)
    return hsv[0][0]

data[['H', 'S', 'V']] = data.apply(
    lambda row: pd.Series(rgb_to_hsv(row)),
    axis=1
)

data.head()

    R   G    B  Label    H    S    V
0  74  85  123      1  113  102  123
1  73  84  122      1  113  102  122
2  72  83  121      1  113  103  121
3  70  81  119      1  113  105  119
4  70  81  119      1  113  105  119

In [5]:
data = data.sample(200000, random_state=42)

In [6]:
X = data[['H', 'S', 'V']]
y = data['Label']

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.891525

In [9]:
import pickle

with open("../models/skin_classifier.pkl", "wb") as f:
    pickle.dump(model, f)